// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wiceuopsdsipsfuptkvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpY2V1b3BzZHNpcHNmdXB0a3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MTE1MjcsImV4cCI6MjA2ODk4NzUyN30.0UUggeNdtASoL9HO3zJ0KlIToyNjATmt3oHqSyNPFZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});